import { chromium } from 'playwright';
const out = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await p.waitForTimeout(800);
await p.click('a[aria-label^="Тема 1."]');
await p.waitForTimeout(1200);
await p.screenshot({ path: out + '/m1-reader-top.png' });
await p.evaluate(() => document.querySelector('.reader__page').scrollBy(0, 700));
await p.waitForTimeout(500);
await p.screenshot({ path: out + '/m2-reader-scrolled.png' });
await b.close();
